name: Build zfs

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - name: install dependencies
        run: sudo apt install build-essential autoconf automake libtool gawk alien fakeroot dkms libblkid-dev uuid-dev libudev-dev libssl-dev zlib1g-dev libaio-dev libattr1-dev libelf-dev linux-headers-$(uname -r) python3 python3-dev python3-setuptools python3-cffi libffi-dev dkms
      - name: Checkout build-zfs
        uses: actions/checkout@v2
        with:
          repository: ethanhs/build-zfs
          path: build-zfs 
      - name: Checkout zfs
        uses: actions/checkout@v2
        with:
          repository: zfsonlinux/zfs
          ref: zfs-0.8.2
          path: zfs
      - run: ./build-zfs/build-zfs.sh
      - run: tar cvf zfs-debs.tar $GITHUB_WORKSPACE/zfs/*.deb
      - uses: actions/upload-artifact@v1
        with:
          name: ZFS Debian packages
          path: zfs-debs.tar
