name: Build zfs

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout build-zfs
        uses: actions/checkout@v2
        with:
          repository: ethanhs/build-zfs
          path: build-zfs 
      - name: Checkout zfs
        uses: actions/checkout@v2
        with:
          repository: zfsonlinux/zfs
          ref: zfs-0.8.2
          path: zfs
      - run: ./build-zfs/build-zfs.sh
