name: Build zfs

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout zfs
      uses: actions/checkout@v2
      with:
        repository: zfsonlinux/zfs
        ref: zfs-0.8.2
        path: zfs
    - name: Checkout build-zfs
      uses: actions/checkout@2
    - run: ./build-zfs.sh
